# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

variables:
  MAVEN_CACHE_FOLDER: /home/user/.m2/repository
  MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'


resources:
  containers:
  - container: flink-build-container
    image: rmetzger/flink-ci:latest

jobs:
- job: runOnASF
  pool:
    name: Default
    #vmImage: 'ubuntu-latest'
  container: flink-build-container
  timeoutInMinutes: 0
  steps:
    # Azure pipelines can only evaluate conditions with the build repo name in the steps.
  - script: exit 1
    condition: eq(variables['Build.Repository.Name'], 'rmetzger/flink') 
  - script: chown -R user:user /home/user
  - script: chown -R user:user .
  - script: ls -lisah $MAVEN_CACHE_FOLDER
#  - script: whoami
#  - script: su user
#    continueOnError: true
#    timeoutInMinutes: 1
#  - script: whoami
  #- script: gosu user mvn clean install
  - script: ls -lisah ; pwd
  - script: ls -lisah /home/user
  - task: CacheBeta@0
    inputs:
      key: maven | **/pom.xml
      path: /home/user/.m2/repository
    displayName: Cache Maven local repo
  - script: ls -lisah $MAVEN_CACHE_FOLDER
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'clean install'
      timeoutInMinutes: 0
      #options: '-X'
  - script: ls -lisah $MAVEN_CACHE_FOLDER
- job: runOnAzure
  pool:
    vmImage: 'ubuntu-latest'
  container: flink-build-container
  timeoutInMinutes: 0
  steps:
  # Azure pipelines can only evaluate conditions with the build repo name in the steps.
  - script: exit 1
    condition: not(eq(variables['Build.Repository.Name'], 'rmetzger/flink'))
  - script: chown -R user:user /home/user
  - script: chown -R user:user .
  - script: ls -lisah $MAVEN_CACHE_FOLDER
#  - script: whoami
#  - script: su user
#    continueOnError: true
#    timeoutInMinutes: 1
#  - script: whoami
  #- script: gosu user mvn clean install
  - script: ls -lisah ; pwd
  - script: ls -lisah /home/user
  - task: CacheBeta@0
    inputs:
      key: maven | **/pom.xml
      path: /home/user/.m2/repository
      securityNamespace: cache
    displayName: Cache Maven local repo
  - script: ls -lisah $MAVEN_CACHE_FOLDER
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'clean install'
      timeoutInMinutes: 0
      #options: '-X'
  - script: ls -lisah $MAVEN_CACHE_FOLDER
